//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5_golobokov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectorReports
    {
        public int ReportID { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string ReportDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual MedicalClaims MedicalClaims { get; set; }
    }
}
