//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5_golobokov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInvoices
    {
        public int InvoiceID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public decimal InvoiceAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual HealthcareInstitutions HealthcareInstitutions { get; set; }
        public virtual MedicalClaims MedicalClaims { get; set; }
    }
}
